### ISSUE TITLE
Doesn't work in a ScrollView

### ISSUE THREAD

**Issue by xsbailong** [skv-headless/react-native-scrollable-tab-view#609] opened 2017-04-16 23:15 UTC
Tried in a normal View, works. But when I put ScrollableTabView component in a ScrollView ; it renders the tabs but not the child elements. 

android, rn0.31 #

**Comment by skv-headless** [comment] 2017-04-17 11:05
duplicate of #187

**Closed by skv-headless** 2017-04-17 11:05 UTC
